#!/bin/sh
#
# kafka       Start/Stop/Restart the Kafka Broker
#
# chkconfig: 345 70 90
# description: Kafka - Apache Kafka is a distributed streaming platform.  \
#              Starts at boot time.
#
### BEGIN INIT INFO
# Provides:          kafka
# Required-Start:    $zookeeper
# Should-Start:
# Required-Stop:     $zookeeper
# Should-Stop:
# Default-Start:     3 4 5
# Default-Stop:      0 1 2 6
# Short-Description: Starts the Kafka Broker
### END INIT INFO

# Init file for acm certificate generation
/usr/bin/acm-pca-cert-generator --key-type RSA --key-length 2048 --subject-c GB --subject-st 'West Yorkshire' --subject-l Leeds  --subject-o 'Department for Work and Pensions' --subject-ou DataWorks --subject-cn 1 --subject-emailaddress 'dataworks@digital.uc.dwp.gov.uk' --ca-arn '${data.terraform_remote_state.certificate_authority.cert_authority.arn}' --signing-algorithm SHA256WITHECDSA --validity-period 1y --keystore-path '/tmp/truststore.jks' --keystore-password '${random_id.truststore_password.hex}' --private-key-alias '${local.environment}' --truststore-path '/tmp/truststore.jks' --truststore-password '${random_id.truststore_password.hex}' --truststore-aliases '${local.environment}' --truststore-certs '${data.terraform_remote_state.certificate_authority.public_cert_bucket.arn}/ca_certificates/dataworks/ca_bundle.pem'

# Init file for Apache Kafka

# pidfile: /var/run/kafka.pid
NAME=kafka
PID_FILE=/var/run/$NAME.pid
KAFKA_USER=kafka
DAEMON="/usr/local/kafka/bin/kafka-server-start.sh"
DAEMON_OPTS="/usr/local/kafka/config/server.properties"
export KAFKA_JMX_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=10020"
export KAFKA_HEAP_OPTS="-Xmx2G -Xms2G"

while [ ! -f /var/run/zookeeper.pid ]
do
    echo zookeeper is not running 
  sleep 2
done
    echo zookeeper is running 
  sleep 15
start() {
  ulimit -n 65536
  ulimit -s 10240
  ulimit -c unlimited
  if [ -f $PID_FILE ]
  then
    PID=`cat $PID_FILE`
    if [ ! -z "`ps -ef | awk '{print $2}' | grep "^$PID$"`" ]
    then
      echo "$PID_FILE exists, process is already running"
      exit 0
    else
      echo "$PID_FILE exists but the process is not running. Deleting $PID_FILE and re-trying"
      rm -f $PID_FILE
      start
    fi
  else
    /sbin/runuser $KAFKA_USER -c "KAFKA_JMX_OPTS=\"$KAFKA_JMX_OPTS\" KAFKA_HEAP_OPTS=\"$KAFKA_HEAP_OPTS\" $DAEMON $DAEMON_OPTS > /var/log/kafka/${NAME}.out 2> /var/log/kafka/${NAME}.err &"
    sleep 2
    PID=`ps ax | grep -E '[k]afka.Kafka' | awk '{print $1}'`
    echo $PID > $PID_FILE;
    echo "$NAME started"
  fi
}
stop() {
  if [ ! -f $PID_FILE ]
  then
    echo "$PID_FILE does not exist, process is not running"
    return 1
  else
    kill `cat $PID_FILE`;
    rm -f $PID_FILE;
    echo "$NAME stopped"
    return 0
  fi
}
status() {
  if [ -f $PID_FILE ]
  then
    PID=`cat $PID_FILE`
    if [ -z "`ps -ef | awk '{print $2}' | grep "^$PID$"`" ]
    then
      echo "$NAME stopped but pid file exists"
      exit 1
    else
      echo "$NAME running with pid $PID"
      exit 0
    fi
  else
    echo "$NAME stopped"
    exit 1
  fi
}
case "$1" in
  status)
    status
	;;
  start)
    echo "Starting daemon: "$NAME
    start
	;;
  stop)
    echo "Stopping daemon: "$NAME
    stop
	;;
  restart)
    echo "Restarting daemon: "$NAME
	  stop
    sleep 5
    start
	;;
  *)
	echo "Usage: "$1" {status|start|stop|restart}"
	exit 1
esac
exit 0
