#!/bin/sh
#
# Init file for Apache Zookeeper
### BEGIN INIT INFO
# Provides:          kafka
# Required-Start:    $zookeeper
# Should-Start:
# Required-Stop:     $zookeeper
# Should-Stop:
# Default-Start:     3 4 5
# Default-Stop:      0 1 2 6
# Short-Description: Kafka Broker
### END INIT INFO
#
# pidfile: /var/run/zookeeper.pid
NAME=zookeeper
PID_FILE=/var/run/$NAME.pid
KAFKA_USER=kafka
DAEMON="/usr/local/kafka/bin/zookeeper-server-start.sh"
DAEMON_OPTS="/usr/local/kafka/config/zookeeper.properties"
start() {
  ulimit -n 65536
  ulimit -s 10240
  ulimit -c unlimited
  if [ -f $PID_FILE ]
  then
    PID=`cat $PID_FILE`
    if [ ! -z "`ps -ef | awk '{print $2}' | grep "^$PID$"`" ]
    then
      echo "$PID_FILE exists, process is already running"
      exit 0
    else
      echo "$PID_FILE exists but the process is not running. Deleting $PID_FILE and re-trying"
      rm -f $PID_FILE
      start
    fi
  else
    /sbin/runuser $KAFKA_USER -c "$DAEMON $DAEMON_OPTS > /var/log/kafka/${NAME}.out 2> /var/log/kafka/${NAME}.err &"
    sleep 2
    PID=`ps ax | grep -E '[z]ookeeper.server' | awk '{print $1}'`
    echo $PID > $PID_FILE;
    echo "$NAME started"
  fi
}
stop() {
  if [ ! -f $PID_FILE ]
  then
    echo "$PID_FILE does not exist, process is not running"
    return 1
  else
    kill `cat $PID_FILE`;
    rm -f $PID_FILE;
    echo "$NAME stopped"
    return 0
  fi
}
status() {
  if [ -f $PID_FILE ]
  then
    PID=`cat $PID_FILE`
    if [ -z "`ps -ef | awk '{print $2}' | grep "^$PID$"`" ]
    then
      echo "$NAME stopped but pid file exists"
      exit 1
    else
      echo "$NAME running with pid $PID"
      exit 0
    fi
  else
    echo "$NAME stopped"
    exit 1
  fi
}
case "$1" in
  status)
    status
	;;
  start)
    echo "Starting daemon: "$NAME
    start
	;;
  stop)
    echo "Stopping daemon: "$NAME
    stop
	;;
  restart)
    echo "Restarting daemon: "$NAME
	  stop
    sleep 2
    start
	;;
  *)
	echo "Usage: "$1" {status|start|stop|restart}"
	exit 1
esac
exit 0
