jobs:
  - name: dw-al2-untested-hardened-ami
    plan:
      - get: dw-al2-untested-hardened-ami
        trigger: false
      - get: dw-al2-hardened-ami-config
        trigger: true
      - get: dw-al2-base-ami-template
        trigger: false
      - get: base-ami-id
        trigger: true
        passed:
          - dw-al2-base-ami
      - .: (( inject meta.plan.generate-manifest ))
        config:
          params:
            AMI_NAME: dw-al2-untested-hardened-ami
            SOURCE_AMI_NAME: dw-al2-base-ami-*
            SOURCE_AMI_OWNER: ((aws_account.management))
            PROVISION_SCRIPT_KEYS: '["dw-al2-hardened-ami-config/dw-al2-hardened-ami/hardening.sh","dw-al2-hardened-ami-config/dw-al2-hardened-ami/dw-hardened-ami-install.sh"]'
            PROVISIONER_TYPE_FILE_SOURCE: "dw-al2-hardened-ami-config/dw-al2-hardened-ami/"
      - .: (( inject meta.plan.packer-bootstrap ))
        input_mapping:
          source_config: dw-al2-hardened-ami-config
          source_template: dw-al2-base-ami-template
      - .: (( inject meta.plan.build-ami ))
        config:
          inputs:
            - name: dw-al2-hardened-ami-config
      - put: hardened-ami-id
        params:
          file: built-ami/id

  - name: dw-al2-hardened-ami-pr
    max_in_flight: 1
    plan:
      - get: dw-al2-hardened-ami-pr
        trigger: true
        version: every
      - get: dw-al2-base-ami-template
        trigger: false
      - get: dw-al2-base-ami
      - put: dw-al2-hardened-ami-pr
        params:
          path: dw-al2-hardened-ami-pr
          status: pending
      - .: (( inject meta.plan.generate-manifest ))
        input_mapping:
          source_ami: dw-al2-base-ami
        config:
          params:
            AMI_NAME: pr-dw-al2-hardened-ami
            SOURCE_AMI_NAME: dw-al2-base-ami-*
            SOURCE_AMI_OWNER: ((aws_account.management))
            AMI_USERS: ((aws_account.development))
            PROVISION_SCRIPT_KEYS: '["dw-al2-hardened-ami-pr/dw-al2-hardened-ami/hardening.sh","dw-al2-hardened-ami-pr/dw-al2-hardened-ami/dw-hardened-ami-install.sh"]'
            PROVISIONER_TYPE_FILE_SOURCE: "dw-al2-hardened-ami-pr/dw-al2-hardened-ami/"
      - .: (( inject meta.plan.packer-bootstrap ))
        input_mapping:
          source_config: dw-al2-hardened-ami-pr
          source_template: dw-al2-base-ami-template
      - .: (( inject meta.plan.build-ami ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
          inputs:
            - name: dw-al2-hardened-ami-pr
        on_failure:
          put: dw-al2-hardened-ami-pr
          params:
            path: dw-al2-hardened-ami-pr
            status: failure
        on_success:
          put: dw-al2-hardened-ami-pr
          params:
            path: dw-al2-hardened-ami-pr
            status: success

  - name: dw-al2-test-and-promote-hardened-ami
    max_in_flight: 1
    plan:
      - get: dw-al2-untested-hardened-ami
        trigger: false
      - get: dw-al2-hardened-ami
        trigger: false
      - get: hardened-ami-id
        trigger: true
        passed:
          - dw-al2-untested-hardened-ami
      - get: aws-management-infrastructure
        trigger: false
      - get: aws-security-tools
        trigger: false
      - .: (( inject meta.plan.terraform-output-management ))
        config:
          params:
            TF_WORKSPACE: management
      - .: (( inject meta.plan.start-instance ))
        input_mapping:
          source_ami: dw-al2-untested-hardened-ami
        config:
          params:
            LAUNCH_TEMPLATE_OUTPUT_NAME: "hardened_test_launch_template"
      - .: (( inject meta.plan.run-inspector ))
      - .: (( inject meta.plan.evaluate-assessment-run))
        config:
          params:
            WHITELIST_NAME: whitelist_al2_hardened_ami
      - .: (( inject meta.plan.promote-ami ))
        input_mapping:
          source_ami: dw-al2-untested-hardened-ami
        config:
          params:
            AMI_NAME_PREFIX: "dw-al2-hardened-ami-"
      - put: hardened-ami-id
        params:
          file: promoted-ami/id
    ensure:
      do:
        - .: (( inject meta.plan.inspector-cleanup ))

  - name: release-and-test-out-of-hours
    max_in_flight: 1
    plan:
      - get: utc-7pm-trigger
        trigger: true
      - get: dw-al2-untested-hardened-ami
        trigger: false
      - get: dw-al2-hardened-ami
        trigger: false
      - get: aws-management-infrastructure
        trigger: false
      - get: aws-security-tools
        trigger: false
      - get: hardened-ami-id
        trigger: trigger
        passed:
          - dw-al2-test-and-promote-hardened-ami

  - name: dw-al2-weekly-test-hardened-ami
    max_in_flight: 1
    plan:
      - get: weekly-wednesday
        trigger: true
      - get: dw-al2-untested-hardened-ami
        trigger: true
      - get: aws-management-infrastructure
        trigger: false
      - get: aws-security-tools
        trigger: false
      - .: (( inject meta.plan.terraform-output-management ))
        config:
          params:
            TF_WORKSPACE: management
      - .: (( inject meta.plan.start-instance ))
        input_mapping:
          source_ami: dw-al2-untested-hardened-ami
        config:
          params:
            LAUNCH_TEMPLATE_OUTPUT_NAME: "hardened_test_launch_template"
      - .: (( inject meta.plan.run-inspector ))
      - .: (( inject meta.plan.evaluate-assessment-run))
        config:
          params:
            WHITELIST_NAME: whitelist_al2_hardened_ami
    ensure:
      do:
        - .: (( inject meta.plan.inspector-cleanup ))
    .: (( inject meta.plan.notify ))
    on_failure:
      params:
        attachments:
          - color: danger
            text: ":fire: Weekly AWS Inspector test of dw-al2-hardened-ami has failed - non-whitelisted vulnerabilities found "
