resources:
  - name: dw-al2-hardened-ami-change
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - dw-al2-hardened-ami/*
  - name: dw-al2-hardened-ami-pr
    .: (( inject meta.resources.ami-builder-configs-pr ))
    source:
      paths:
        - dw-al2-hardened-ami/*

jobs:
  - name: dw-al2-untested-hardened-ami
    plan:
      - get: dw-al2-hardened-ami-change
        trigger: true
      - get: packer-dw-al2-general-ami
        trigger: true
      - .: (( inject meta.plan.generate-manifest ))
        input_mapping:
          source_ami: packer-dw-al2-general-ami
        config:
          inputs:
            - name: source_ami
          params:
            AMI_NAME: packer-dw-al2-untested-hardened-ami
            INSTANCE_TYPE: t2.micro
            PACKER_TEMPLATE_KEY: generic_packer_template.json.j2
            PROVISION_SCRIPT_KEYS: '["dw-al2-hardened-ami-change/dw-al2-hardened-ami/hardening.sh","dw-al2-hardened-ami-change/dw-al2-hardened-ami/dw-hardened-ami-install.sh"]'
            PROVISIONER_TYPE_FILE_SOURCE: "dw-al2-hardened-ami-change/dw-al2-hardened-ami/"
            SET_PROXY: true
            SOURCE_AMI_NAME: packer-dw-al2-general-ami-*
            SOURCE_AMI_OWNER: ((aws_account.management))
      - .: (( inject meta.plan.packer-bootstrap ))
        config:
          run:
            dir: dw-al2-hardened-ami-change
          inputs:
            - name: dw-al2-hardened-ami-change
      - .: (( inject meta.plan.build-ami ))
        config:
          inputs:
            - name: dw-al2-hardened-ami-change

  - name: dw-al2-hardened-ami-pr
    max_in_flight: 1
    plan:
      - get: dw-al2-hardened-ami-pr
        trigger: true
        version: every
      - get: packer-dw-al2-general-ami
      - put: dw-al2-hardened-ami-pr
        params:
          path: dw-al2-hardened-ami-pr
          status: pending
      - .: (( inject meta.plan.generate-manifest ))
        input_mapping:
          source_ami: packer-dw-al2-general-ami
        config:
          inputs:
            - name: source_ami
          params:
            AMI_NAME: packer-pr-dw-al2-hardened-ami
            INSTANCE_TYPE: t2.micro
            PACKER_TEMPLATE_KEY: generic_packer_template.json.j2
            PROVISION_SCRIPT_KEYS: '["dw-al2-hardened-ami-pr/dw-al2-hardened-ami/hardening.sh","dw-al2-hardened-ami-pr/dw-al2-hardened-ami/dw-hardened-ami-install.sh"]'
            PROVISIONER_TYPE_FILE_SOURCE: "dw-al2-hardened-ami-pr/dw-al2-hardened-ami/"
            SET_PROXY: true
            SOURCE_AMI_NAME: packer-dw-al2-general-ami-*
            SOURCE_AMI_OWNER: ((aws_account.management))
            AMI_USERS: ((aws_account.development))
      - .: (( inject meta.plan.packer-bootstrap ))
        config:
          run:
            dir: dw-al2-hardened-ami-pr
          inputs:
            - name: dw-al2-hardened-ami-pr
      - .: (( inject meta.plan.build-ami ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
          inputs:
            - name: dw-al2-hardened-ami-pr
        on_failure:
          put: dw-al2-hardened-ami-pr
          params:
            path: dw-al2-hardened-ami-pr
            status: failure
        on_success:
          put: dw-al2-hardened-ami-pr
          params:
            path: dw-al2-hardened-ami-pr
            status: success

  - name: dw-al2-test-and-promote-hardened-ami
    max_in_flight: 1
    plan:
      - get: packer-dw-al2-untested-hardened-ami
        trigger: true
      - get: aws-management-infrastructure
        trigger: false
      - get: aws-security-tools
        trigger: false
      - .: (( inject meta.plan.terraform-output-management ))
        config:
          params:
            TF_WORKSPACE: management
      - .: (( inject meta.plan.start-instance ))
        input_mapping:
          source_ami: packer-dw-al2-untested-hardened-ami
        config:
          params:
            LAUNCH_TEMPLATE_OUTPUT_NAME: "hardened_test_launch_template"
      - .: (( inject meta.plan.run-inspector ))
      - .: (( inject meta.plan.evaluate-assessment-run))
        config:
          params:
            WHITELIST_NAME: whitelist_al2_hardened_ami
      - .: (( inject meta.plan.promote-ami ))
        input_mapping:
          source_ami: packer-dw-al2-untested-hardened-ami
        config:
          params:
            AMI_NAME_PREFIX: "packer-dw-al2-hardened-ami-"
    ensure:
      do:
        - .: (( inject meta.plan.inspector-cleanup ))

  - name: dw-al2-weekly-test-hardened-ami
    max_in_flight: 1
    plan:
      - get: weekly-wednesday
        trigger: true
      - get: packer-dw-al2-untested-hardened-ami
        trigger: true
      - get: aws-management-infrastructure
        trigger: false
      - get: aws-security-tools
        trigger: false
      - .: (( inject meta.plan.terraform-output-management ))
        config:
          params:
            TF_WORKSPACE: management
      - .: (( inject meta.plan.start-instance ))
        input_mapping:
          source_ami: packer-dw-al2-untested-hardened-ami
        config:
          params:
            LAUNCH_TEMPLATE_OUTPUT_NAME: "hardened_test_launch_template"
      - .: (( inject meta.plan.run-inspector ))
      - .: (( inject meta.plan.evaluate-assessment-run))
        config:
          params:
            WHITELIST_NAME: whitelist_al2_hardened_ami
    ensure:
      do:
        - .: (( inject meta.plan.inspector-cleanup ))
    on_failure:
      put: slack
      attempts: 3
      params:
        channel: "#dataworks-alerts"
        icon_emoji: ":concourse-red:"
        attachments:
          - color: danger
            text: ":fire: Weekly AWS Inspector test of dw-al2-hardened-ami has failed - non-whitelisted vulnerabilities found "
            attachment_type: "default"
