jobs:
  - name: dw-al2-base-ami
    plan:
      - get: amzn2-ami-hvm
        trigger: true
      - get: dw-al2-base-ami-config
        trigger: true
      - get: dw-al2-base-ami-template
        trigger: true
      - get: dw-al2-base-ami
        trigger: false
      - .: (( inject meta.plan.generate-manifest ))
        config:
          params:
            AMI_NAME: dw-al2-base-ami
            PROVISION_SCRIPT_KEYS: '["dw-al2-base-ami-config/dw-al2-base-ami/dw-base-ami-install.sh"]'
            PROVISIONER_TYPE_FILE_SOURCE: "dw-al2-base-ami-config/dw-al2-base-ami/"
            SOURCE_AMI_NAME: "amzn2-ami-hvm-*"
            SOURCE_AMI_OWNER: "137112412989"
            HCS_COMPLIANT: true
      - .: (( inject meta.plan.packer-bootstrap ))
        input_mapping:
          source_config: dw-al2-base-ami-config
          source_template: dw-al2-base-ami-template
      - .: (( inject meta.plan.build-ami ))
        config:
          inputs:
            - name: dw-al2-base-ami-config
      - put: base-ami-id
        params:
          file: built-ami/id

  - name: dw-al2-hcs-backed-singlevol-ami
    plan:
      - get: hcs-amzn2-singlevol-cis2-ami
        trigger: true
      - get: dw-al2-base-ami-config
        trigger: true
      - get: dw-al2-base-ami-template
        trigger: true
      - .: (( inject meta.plan.generate-manifest ))
        config:
          params:
            AMI_NAME: dw-al2-hcs-backed-singlevol-ami
            PROVISION_SCRIPT_KEYS: '["dw-al2-base-ami-config/dw-al2-base-ami/dw-base-ami-install.sh"]'
            PROVISIONER_TYPE_FILE_SOURCE: "dw-al2-base-ami-config/dw-al2-base-ami/"
            SOURCE_AMI_NAME: "AMZN2-SINGLEVOL-AWS-CIS2-2022*"
            SOURCE_AMI_OWNER: "((dataworks.hcs_aws_account))"
            HCS_COMPLIANT: true
      - .: (( inject meta.plan.packer-bootstrap ))
        input_mapping:
          source_config: dw-al2-base-ami-config
          source_template: dw-al2-base-ami-template
      - .: (( inject meta.plan.build-ami ))
        config:
          inputs:
            - name: dw-al2-base-ami-config
      - put: hcs-backed-singlevol-ami-id
        params:
          file: built-ami/id

  - name: dw-al2-hcs-backed-dualvol-ami
    plan:
      - get: hcs-amzn2-cis2-ami
        trigger: true
      - get: dw-al2-base-ami-config
        trigger: true
      - get: dw-al2-base-ami-template
        trigger: true
      - .: (( inject meta.plan.generate-manifest ))
        config:
          params:
            AMI_NAME: dw-al2-hcs-backed-dualvol-ami
            PROVISION_SCRIPT_KEYS: '["dw-al2-base-ami-config/dw-al2-base-ami/dw-base-ami-install.sh"]'
            PROVISIONER_TYPE_FILE_SOURCE: "dw-al2-base-ami-config/dw-al2-base-ami/"
            SOURCE_AMI_NAME: "AMZN2-AWS-CIS2-2022*"
            SOURCE_AMI_OWNER: "((dataworks.hcs_aws_account))"
            HCS_COMPLIANT: true
      - .: (( inject meta.plan.packer-bootstrap ))
        input_mapping:
          source_config: dw-al2-base-ami-config
          source_template: dw-al2-base-ami-template
      - .: (( inject meta.plan.build-ami ))
        config:
          inputs:
            - name: dw-al2-base-ami-config
      - put: hcs-backed-dualvol-ami-id
        params:
          file: built-ami/id

  - name: dw-al2-hcs-backed-ami-pr
    max_in_flight: 1
    plan:
      - get: hcs-amzn2-cis2-ami
        trigger: false
      - get: hcs-amzn2-singlevol-cis2-ami
        trigger: false
      - get: dw-al2-base-ami-pr
        trigger: true
      - put: dw-al2-base-ami-pr
        params:
          path: dw-al2-base-ami-pr
          status: pending
      - .: (( inject meta.plan.generate-manifest ))
        config:
          params:
            AMI_NAME: pr-dw-al2-hcs-backed-dualvol-ami
            AMI_USERS: ((aws_account.development))
            PROVISION_SCRIPT_KEYS: '["dw-al2-base-ami-pr/dw-al2-base-ami/dw-base-ami-install.sh"]'
            PROVISIONER_TYPE_FILE_SOURCE: "dw-al2-base-ami-pr/dw-al2-base-ami/"
            SOURCE_AMI_NAME: "AMZN2-AWS-CIS2-2022*"
            SOURCE_AMI_OWNER: "((dataworks.hcs_aws_account))"
            HCS_COMPLIANT: true
      - .: (( inject meta.plan.packer-bootstrap ))
        input_mapping:
          source_config: dw-al2-base-ami-pr
      - .: (( inject meta.plan.build-ami ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
          inputs:
            - name: dw-al2-base-ami-pr
      - .: (( inject meta.plan.generate-manifest ))
        config:
          params:
            AMI_NAME: pr-dw-al2-hcs-backed-singlevol-ami
            AMI_USERS: ((aws_account.development))
            PROVISION_SCRIPT_KEYS: '["dw-al2-base-ami-pr/dw-al2-base-ami/dw-base-ami-install.sh"]'
            PROVISIONER_TYPE_FILE_SOURCE: "dw-al2-base-ami-pr/dw-al2-base-ami/"
            SOURCE_AMI_NAME: "AMZN2-SINGLEVOL-AWS-CIS2-2022*"
            SOURCE_AMI_OWNER: "((dataworks.hcs_aws_account))"
      - .: (( inject meta.plan.packer-bootstrap ))
        input_mapping:
          source_config: dw-al2-base-ami-pr
      - .: (( inject meta.plan.build-ami ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
          inputs:
            - name: dw-al2-base-ami-pr
        on_failure:
          put: dw-al2-base-ami-pr
          params:
            path: dw-al2-base-ami-pr
            status: failure
        on_success:
          put: dw-al2-base-ami-pr
          params:
            path: dw-al2-base-ami-pr
            status: success


  - name: release-and-test-out-of-hours
    max_in_flight: 1
    plan:
      - get: utc-7pm-trigger
        trigger: true
      - get: dw-al2-emr-ami
        trigger: true
      - get: hcs-backed-singlevol-ami-id
        trigger: true
        passed:
          - dw-al2-hcs-backed-singlevol-ami
      - get: hcs-backed-dualvol-ami-id
        trigger: true
        passed:
          - dw-al2-hcs-backed-dualvol-ami
      - get: hcs-backed-emr-ami-id
        trigger: true
        passed:
          - dw-al2-hcs-backed-emr-ami
      - get: hardened-ami-id
        trigger: true
        passed:
          - dw-al2-test-and-promote-hardened-ami