resources:
  - name: dw-al2-emr-ami-config
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - dw-al2-emr-ami/*
        - ci/infra/jobs/build_amis/dw-al2-emr-ami.yml

  - name: dw-al2-emr-ami-pr
    .: (( inject meta.resources.ami-builder-configs-pr ))
    source:
      paths:
        - dw-al2-emr-ami/*
        - ci/infra/jobs/build_amis/dw-al2-emr-ami.yml
  
  - name: aws-analytical-dataset-generation
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - results/aws-analytical-dataset-generation.test

jobs:
  - name: untested-dw-al2-emr-ami
    plan:
      - get: dw-al2-emr-ami-config
        trigger: true
      - get: dw-al2-base-ami-template
        trigger: false
        passed:
          - dw-al2-test-and-promote-hardened-ami
      - .: (( inject meta.plan.get-al2-hardened-ami ))
        trigger: true
      - .: (( inject meta.plan.generate-manifest ))
        input_mapping:
          source_ami: dw-al2-hardened-ami
        config:
          params:
            AMI_NAME: untested-dw-al2-emr-ami
            SOURCE_AMI_NAME: dw-al2-hardened-ami-*
            SOURCE_AMI_OWNER: ((aws_account.management))
            PROVISION_SCRIPT_KEYS: '["dw-al2-emr-ami-config/dw-al2-emr-ami/dw-emr-ami-install.sh"]'
            PROVISIONER_TYPE_FILE_SOURCE: "dw-al2-emr-ami-config/dw-al2-emr-ami/"
      - .: (( inject meta.plan.packer-bootstrap ))
        input_mapping:
          source_config: dw-al2-emr-ami-config
          source_template: dw-al2-base-ami-template
      - .: (( inject meta.plan.build-ami ))
        config:
          inputs:
            - name: dw-al2-hardened-ami-config
      # - .: (( inject meta.plan.put-current-ami ))
      #   config:
      #     inputs:
      #       - name: built-ami
      #     params:
      #       SERVICE: emr
        

  - name: validate-emr-ami
    plan:
      - get: untested-dw-al2-emr-ami
        trigger: false
      - get: dw-al2-base-ami-template
        trigger: false
        passed:
          - untested-dw-al2-emr-ami
      - get: aws-analytical-dataset-generation
        trigger: true
      - .: (( inject meta.plan.validate-ami ))
        config:
          params:
            SERVICE: emr

  - name: dw-al2-emr-ami
    plan:
      - get: untested-dw-al2-emr-ami
        trigger: true
        passed:
          - validate-emr-ami
      - .: (( inject meta.plan.promote-ami ))
        input_mapping:
          source_ami: untested-dw-al2-emr-ami
        config:
          params:
            AMI_NAME_PREFIX: "dw-al2-emr-ami-"

  - name: dw-al2-emr-ami-pr
    max_in_flight: 1
    plan:
      - get: dw-al2-emr-ami-pr
        trigger: true
        version: every
      - get: dw-al2-base-ami-template
        trigger: false
      - put: dw-al2-emr-ami-pr
        params:
          path: dw-al2-emr-ami-pr
          status: pending
      - .: (( inject meta.plan.get-al2-hardened-ami ))
        trigger: false
      - .: (( inject meta.plan.generate-manifest ))
        input_mapping:
          source_ami: dw-al2-hardened-ami
        config:
          params:
            AMI_NAME: pr-dw-al2-emr-ami
            SOURCE_AMI_NAME: dw-al2-hardened-ami-*
            SOURCE_AMI_OWNER: ((aws_account.management))
            AMI_USERS: ((aws_account.development))
            PROVISION_SCRIPT_KEYS: '["dw-al2-emr-ami-pr/dw-al2-emr-ami/dw-emr-ami-install.sh"]'
            PROVISIONER_TYPE_FILE_SOURCE: "dw-al2-emr-ami-pr/dw-al2-emr-ami/"
      - .: (( inject meta.plan.packer-bootstrap ))
        input_mapping:
          source_config: dw-al2-emr-ami-pr
          source_template: dw-al2-base-ami-template
      - .: (( inject meta.plan.build-ami ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
          inputs:
            - name: dw-al2-emr-ami-pr
        on_failure:
          put: dw-al2-emr-ami-pr
          params:
            path: dw-al2-emr-ami-pr
            status: failure
        on_success:
          put: dw-al2-emr-ami-pr
          params:
            path: dw-al2-emr-ami-pr
            status: success
