resources:
  - name: dw-al2-ecs-ami-change
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - dw-al2-ecs-ami/*
  - name: dw-al2-ecs-ami-pr
    .: (( inject meta.resources.ami-builder-configs-pr ))
    source:
      paths:
        - dw-al2-ecs-ami/*

jobs:
  - name: dw-al2-ecs-ami
    plan:
      - get: dw-al2-ecs-ami-change
        trigger: true
      - .: (( inject meta.plan.get-al2-hardened-ami ))
      - .: (( inject meta.plan.generate-manifest ))
        input_mapping:
          source_ami: packer-dw-al2-hardened-ami
        config:
          inputs:
            - name: source_ami
          params:
            AMI_NAME: packer-dw-al2-ecs-ami
            INSTANCE_TYPE: t2.micro
            PACKER_TEMPLATE_KEY: generic_packer_template.json.j2
            PROVISION_SCRIPT_KEYS: '["dw-al2-ecs-ami-change/dw-al2-ecs-ami/dw-ecs-ami-install.sh"]'
            PROVISIONER_TYPE_FILE_SOURCE: "dw-al2-ecs-ami-change/dw-al2-ecs-ami/dw-ecs-ami-install.sh"
            SET_PROXY: true
            SOURCE_AMI_NAME: packer-dw-al2-hardened-ami-*
            SOURCE_AMI_OWNER: ((aws_account.management))
      - .: (( inject meta.plan.packer-bootstrap ))
        config:
          run:
            dir: dw-al2-ecs-ami-change
          inputs:
            - name: dw-al2-ecs-ami-change
      - .: (( inject meta.plan.build-ami ))
        config:
          inputs:
            - name: dw-al2-ecs-ami-change

  - name: dw-al2-ecs-ami-pr
    max_in_flight: 1
    plan:
      - get: dw-al2-ecs-ami-pr
        trigger: true
        version: every
      - put: dw-al2-ecs-ami-pr
        params:
          path: dw-al2-ecs-ami-pr
          status: pending
      - .: (( inject meta.plan.get-al2-hardened-ami ))
      - .: (( inject meta.plan.generate-manifest ))
        input_mapping:
          source_ami: packer-dw-al2-hardened-ami
        config:
          inputs:
            - name: source_ami
          params:
            AMI_NAME: packer-pr-dw-al2-ecs-ami
            INSTANCE_TYPE: t2.micro
            PACKER_TEMPLATE_KEY: generic_packer_template.json.j2
            PROVISION_SCRIPT_KEYS: '["dw-al2-ecs-ami-pr/dw-al2-ecs-ami/dw-ecs-ami-install.sh"]'
            PROVISIONER_TYPE_FILE_SOURCE: "dw-al2-ecs-ami-pr/dw-al2-ecs-ami/dw-ecs-ami-install.sh"
            SET_PROXY: true
            SOURCE_AMI_NAME: packer-dw-al2-hardened-ami-*
            SOURCE_AMI_OWNER: ((aws_account.management))
            AMI_USERS: ((aws_account.development))
      - .: (( inject meta.plan.packer-bootstrap ))
        config:
          run:
            dir: dw-al2-ecs-ami-pr
          inputs:
            - name: dw-al2-ecs-ami-pr
      - .: (( inject meta.plan.build-ami ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
          inputs:
            - name: dw-al2-ecs-ami-pr
        on_failure:
          put: dw-al2-ecs-ami-pr
          params:
            path: dw-al2-ecs-ami-pr
            status: failure
        on_success:
          put: dw-al2-ecs-ami-pr
          params:
            path: dw-al2-ecs-ami-pr
            status: success
