jobs:
  - name: untested-dw-al2-emr-ami
    plan:
      - get: base-ami-id
        trigger: true
        passed:
          - release-and-test-out-of-hours
          -  dw-al2-base-ami
      - get: dw-al2-emr-ami-config
        trigger: true
      - get: dw-al2-base-ami-template
        trigger: false
      - .: (( inject meta.plan.generate-manifest ))
        config:
          params:
            AMI_NAME: untested-dw-al2-emr-ami
            SOURCE_AMI_NAME: dw-al2-base-ami-*
            SOURCE_AMI_OWNER: ((aws_account.management))
            PROVISION_SCRIPT_KEYS: '["dw-al2-emr-ami-config/dw-al2-emr-ami/dw-emr-ami-install.sh"]'
            PROVISIONER_TYPE_FILE_SOURCE: "dw-al2-emr-ami-config/dw-al2-emr-ami/"
      - .: (( inject meta.plan.packer-bootstrap ))
        input_mapping:
          source_config: dw-al2-emr-ami-config
          source_template: dw-al2-base-ami-template
      - .: (( inject meta.plan.build-ami ))
        config:
          inputs:
            - name: dw-al2-emr-ami-config
      - put: untested-dw-al2-emr-ami
        params:
          file: built-ami/id

  - name: validate-emr-ami
    plan:
      - get: untested-dw-al2-emr-ami
        trigger: true
        passed:
          - untested-dw-al2-emr-ami
      - get: analytical-dataset-generation
        trigger: true
      - get: pdm-dataset-generation
        trigger: true
      - get: aws-clive
        trigger: true
      - get: aws-cyi-infrastructure
        trigger: true
      - get: aws-mongo-latest
        trigger: true
      - get: dataworks-aws-kickstart-adg
        trigger: true
      - get: aws-uc-feature-infrastructure
        trigger: true
      - .: (( inject meta.plan.validate-ami ))
        config:
          params:
            UNTESTED_AMI: untested-dw-al2-emr-ami
          inputs:
            - name: untested-dw-al2-emr-ami
            - name: analytical-dataset-generation
            - name: pdm-dataset-generation
            - name: aws-clive
            - name: aws-mongo-latest
            - name: dataworks-aws-kickstart-adg
            - name: aws-uc-feature-infrastructure
            - name: aws-cyi-infrastructure
      - put: emr-ami-id
        params:
          file: tested_ami/id

  - name: dw-al2-emr-ami
    plan:
      - get: source_ami
        resource: emr-ami-id
        trigger: true
        passed:
          - validate-emr-ami
      - .: (( inject meta.plan.promote-ami ))
        config:
          params:
            AMI_NAME_PREFIX: "dw-al2-emr-ami-"

  - name: dw-al2-emr-ami-pr
    max_in_flight: 1
    plan:
      - get: dw-al2-emr-ami-pr
        trigger: true
        version: every
      - get: dw-al2-base-ami-template-pr
        trigger: false
      - put: dw-al2-emr-ami-pr
        params:
          path: dw-al2-emr-ami-pr
          status: pending
      - get: base-ami-id
        trigger: false
      - .: (( inject meta.plan.generate-manifest ))
        input_mapping:
          source_ami: base-ami-id
        config:
          params:
            AMI_NAME: pr-dw-al2-emr-ami
            SOURCE_AMI_NAME: dw-al2-base-ami-*
            SOURCE_AMI_OWNER: ((aws_account.management))
            AMI_USERS: ((aws_account.development))
            PROVISION_SCRIPT_KEYS: '["dw-al2-emr-ami-pr/dw-al2-emr-ami/dw-emr-ami-install.sh"]'
            PROVISIONER_TYPE_FILE_SOURCE: "dw-al2-emr-ami-pr/dw-al2-emr-ami/"
      - .: (( inject meta.plan.packer-bootstrap ))
        input_mapping:
          source_config: dw-al2-emr-ami-pr
          source_template: dw-al2-base-ami-template-pr
      - .: (( inject meta.plan.build-ami ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
          inputs:
            - name: dw-al2-emr-ami-pr
        on_failure:
          put: dw-al2-emr-ami-pr
          params:
            path: dw-al2-emr-ami-pr
            status: failure
        on_success:
          put: dw-al2-emr-ami-pr
          params:
            path: dw-al2-emr-ami-pr
            status: success
