jobs:
  - name: untested-dw-al2-concourse-ami
    plan:
      - .: (( inject meta.plan.get-concourse-release ))
      - get: base-ami-id
        trigger: true
        passed:
          - release-and-test-out-of-hours
      - get: dw-al2-concourse-ami-config
        trigger: true
      - get: dw-al2-base-ami-template
        trigger: false
      - .: (( inject meta.plan.generate-manifest ))
        config:
          params:
            AMI_NAME: untested-dw-al2-concourse-ami
            SOURCE_AMI_NAME: dw-al2-base-ami-*
            SOURCE_AMI_OWNER: ((aws_account.management))
            PROVISION_SCRIPT_KEYS: '["dw-al2-concourse-ami-config/dw-al2-concourse-ami/dw-concourse-ami-install.sh"]'
            PROVISIONER_TYPE_FILE_SOURCE: "dw-al2-concourse-ami-config/dw-al2-concourse-ami/"
          inputs:
            - name: concourse-release
      - .: (( inject meta.plan.packer-bootstrap ))
        input_mapping:
          source_config: dw-al2-concourse-ami-config
          source_template: dw-al2-base-ami-template
      - .: (( inject meta.plan.build-ami ))
        config:
          inputs:
            - name: dw-al2-concourse-ami-config
            - name: concourse-release
      - put: untested-dw-al2-concourse-ami
        params:
          file: built-ami/id

  - name: validate-concourse-ami
    plan:
      - get: untested-dw-al2-concourse-ami
        trigger: true
        passed:
          - untested-dw-al2-concourse-ami
      - get: concourse
        trigger: true
      - .: (( inject meta.plan.validate-ami ))
        config:
          params:
            UNTESTED_AMI: untested-dw-al2-concourse-ami
          inputs:
            - name: untested-dw-al2-concourse-ami
            - name: concourse
      - put: concourse-ami-id
        params:
          file: tested_ami/id

  - name: dw-al2-concourse-ami
    plan:
      - get: source_ami
        resource: concourse-ami-id
        trigger: true
        passed:
          - validate-concourse-ami
      - .: (( inject meta.plan.promote-ami ))
        config:
          params:
            AMI_NAME_PREFIX: "dw-al2-concourse-ami-"

  - name: dw-al2-concourse-ami-pr
    max_in_flight: 1
    plan:
      - get: dw-al2-concourse-ami-pr
        trigger: true
        version: every
      - get: dw-al2-base-ami-template
        trigger: false
      - put: dw-al2-concourse-ami-pr
        params:
          path: dw-al2-concourse-ami-pr
          status: pending
      - get: dw-al2-base-ami
        trigger: false
      - .: (( inject meta.plan.generate-manifest ))
        input_mapping:
          source_ami: dw-al2-base-ami
        config:
          params:
            AMI_NAME: pr-dw-al2-concourse-ami
            SOURCE_AMI_NAME: dw-al2-base-ami-*
            SOURCE_AMI_OWNER: ((aws_account.management))
            AMI_USERS: ((aws_account.development))
            PROVISION_SCRIPT_KEYS: '["dw-al2-concourse-ami-pr/dw-al2-concourse-ami/dw-concourse-ami-install.sh"]'
            PROVISIONER_TYPE_FILE_SOURCE: "dw-al2-concourse-ami-pr/dw-al2-concourse-ami/"
      - .: (( inject meta.plan.packer-bootstrap ))
        input_mapping:
          source_config: dw-al2-concourse-ami-pr
          source_template: dw-al2-base-ami-template
      - .: (( inject meta.plan.build-ami ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
          inputs:
            - name: dw-al2-concourse-ami-pr
        on_failure:
          put: dw-al2-concourse-ami-pr
          params:
            path: dw-al2-concourse-ami-pr
            status: failure
        on_success:
          put: dw-al2-concourse-ami-pr
          params:
            path: dw-al2-concourse-ami-pr
            status: success
