resources:
  - name: dw-al2-concourse-ami-change
    .: (( inject meta.resources.ami-builder-configs-repo ))
    source:
      paths:
        - dw-al2-concourse-ami/*
  - name: dw-al2-concourse-ami-pr
    .: (( inject meta.resources.ami-builder-configs-repo-pr ))
    source:
      paths:
        - dw-al2-concourse-ami/*

jobs:
  - name: dw-al2-concourse-ami
    plan:
      - get: dw-al2-concourse-ami-change
        trigger: true
      - .: (( inject meta.plan.get-al2-hardened-ami ))
      - .: (( inject meta.plan.generate-manifest ))
        input_mapping:
          source_ami: dw-al2-hardened-ami
        config:
          inputs:
            - name: source_ami
          params:
            AMI_NAME: packer-dw-al2-concourse-ami
            INSTANCE_TYPE: t2.micro
            PACKER_TEMPLATE_KEY: ami-builder/dw-al2-concourse-ami/generic_packer_template.json.j2
            PROVISION_SCRIPT_KEYS: '["ami-builder/dw-al2-concourse-ami/dw-concourse-ami-install.sh"]'
            SET_PROXY: true
            SOURCE_AMI_NAME: packer-dw-al2-hardened-ami-*
            SOURCE_AMI_OWNER: ((aws_account.management))
            CONCOURSE_VERSION: 6.4.1
      - .: (( inject meta.plan.packer-bootstrap ))
      - .: (( inject meta.plan.build-ami ))

  - name: dw-al2-concourse-ami-pr
    max_in_flight: 1
    plan:
      - get: dw-al2-concourse-ami-pr
        trigger: true
        version: every
      - put: dw-al2-concourse-ami-pr
        params:
          path: dw-al2-concourse-ami-pr
          status: pending
      - get: aws-management-infrastructure
      - .: (( inject meta.plan.terraform-output-management ))
      - .: (( inject meta.plan.get-al2-hardened-ami ))
      - .: (( inject meta.plan.generate-manifest-mgt-dev-pr ))
        input_mapping:
          source_ami: dw-al2-hardened-ami
        config:
          inputs:
            - name: source_ami
          params:
            AMI_NAME: packer-pr-dw-al2-concourse-ami
            INSTANCE_TYPE: t2.micro
            PACKER_TEMPLATE_KEY: ami-builder/pr/dw-al2-concourse-ami/generic_packer_template.json.j2
            PROVISION_SCRIPT_KEYS: '["ami-builder/pr/dw-al2-concourse-ami/dw-concourse-ami-install.sh"]'
            SET_PROXY: true
            SOURCE_AMI_NAME: packer-dw-al2-hardened-ami-*
            SOURCE_AMI_OWNER: ((aws_account.management))
            AMI_USERS: ((aws_account.development))
            CONCOURSE_VERSION: 6.5.1
      - .: (( inject meta.plan.packer-bootstrap ))
      - .: (( inject meta.plan.build-ami ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.management-dev)):role/ci
        on_failure:
          put: dw-al2-concourse-ami-pr
          params:
            path: dw-al2-concourse-ami-pr
            status: failure
        on_success:
          put: dw-al2-concourse-ami-pr
          params:
            path: dw-al2-concourse-ami-pr
            status: success
