jobs:
  - name: dw-al2-base-emr-ami
    plan:
      - get: hcs-amzn2emr-cis2-ami
        trigger: true
      - get: dw-al2-base-ami-config
        trigger: true
      - get: dw-al2-base-ami-template
        trigger: true
      - .: (( inject meta.plan.generate-manifest ))
        config:
          params:
            AMI_NAME: dw-al2-base-emr-ami
            PROVISION_SCRIPT_KEYS: '["dw-al2-base-ami-config/dw-al2-base-ami/dw-base-ami-install.sh"]'
            PROVISIONER_TYPE_FILE_SOURCE: "dw-al2-base-ami-config/dw-al2-base-ami/"
            SOURCE_AMI_NAME: "AMZN2EMR-AWS-CIS2-2022*"
            SOURCE_AMI_OWNER: "((dataworks.hcs_aws_account))"
            HCS_COMPLIANT: true
      - .: (( inject meta.plan.packer-bootstrap ))
        input_mapping:
          source_config: dw-al2-base-ami-config
          source_template: dw-al2-base-ami-template
      - .: (( inject meta.plan.build-ami ))
        config:
          inputs:
            - name: dw-al2-base-ami-config
      - put: base-emr-ami-id
        params:
          file: built-ami/id

  - name: dw-al2-base-emr-ami-pr
    max_in_flight: 1
    plan:
      - get: hcs-amzn2emr-cis2-ami
        trigger: false
      - get: dw-al2-base-ami-pr
        trigger: true
      - get: dw-al2-base-ami-template-pr
        trigger: false
      - put: dw-al2-base-ami-pr
        params:
          path: dw-al2-base-ami-pr
          status: pending
      - .: (( inject meta.plan.generate-manifest ))
        config:
          params:
            AMI_NAME: pr-dw-al2-base-emr-ami
            AMI_USERS: ((aws_account.development))
            PROVISION_SCRIPT_KEYS: '["dw-al2-base-ami-pr/dw-al2-base-ami/dw-base-ami-install.sh"]'
            PROVISIONER_TYPE_FILE_SOURCE: "dw-al2-base-ami-pr/dw-al2-base-ami/"
            SOURCE_AMI_NAME: "AMZN2EMR-AWS-CIS2-2022*"
            SOURCE_AMI_OWNER: "((dataworks.hcs_aws_account))"
            HCS_COMPLIANT: true
      - .: (( inject meta.plan.packer-bootstrap ))
        input_mapping:
          source_config: dw-al2-base-ami-pr
          source_template: dw-al2-base-ami-template-pr
      - .: (( inject meta.plan.build-ami ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
          inputs:
            - name: dw-al2-base-ami-pr
        on_failure:
          put: dw-al2-base-ami-pr
          params:
            path: dw-al2-base-ami-pr
            status: failure
        on_success:
          put: dw-al2-base-ami-pr
          params:
            path: dw-al2-base-ami-pr
            status: success
