jobs:
  - name: untested-dw-al2-ecs-ami
    plan:
      - get: hardened-ami-id
        trigger: true
        passed:
          - dw-al2-test-and-promote-hardened-ami
          - release-and-test-out-of-hours
      - get: dw-al2-ecs-ami-config
        trigger: true
      - get: dw-al2-base-ami-template
        trigger: false
      - get: dw-al2-hardened-ami-config
        trigger: false
      - .: (( inject meta.plan.generate-manifest ))
        config:
          params:
            AMI_NAME: untested-dw-al2-ecs-ami
            SOURCE_AMI_NAME: dw-al2-hardened-ami-*
            SOURCE_AMI_OWNER: ((aws_account.management))
            PROVISION_SCRIPT_KEYS: '["dw-al2-ecs-ami-config/dw-al2-ecs-ami/dw-ecs-ami-install.sh"]'
            PROVISIONER_TYPE_FILE_SOURCE: "dw-al2-ecs-ami-config/dw-al2-ecs-ami/"
      - .: (( inject meta.plan.packer-bootstrap ))
        input_mapping:
          source_config: dw-al2-hardened-ami-config
          source_template: dw-al2-base-ami-template
      - .: (( inject meta.plan.build-ami ))
        config:
          inputs:
            - name: dw-al2-ecs-ami-config
      - put: untested-dw-al2-ecs-ami
        params:
          file: built-ami/id

  - name: validate-ecs-ami
    plan:
      - get: untested-dw-al2-ecs-ami
        trigger: true
        passed:
          - untested-dw-al2-ecs-ami
      - get: metrics-infrastructure
        trigger: true
      - get: orchestration-service
        trigger: true
      - get: ingestion-ecs-cluster
        trigger: true
      - get: data-egress
        trigger: true
      - get: s3-object-tagger-infra
        trigger: true
      - .: (( inject meta.plan.validate-ami ))
        config:
          params:
            UNTESTED_AMI: untested-dw-al2-ecs-ami
          inputs:
            - name: untested-dw-al2-ecs-ami
            - name: metrics-infrastructure
            - name: ingestion-ecs-cluster
            - name: data-egress
            - name: orchestration-service
            - name: s3-object-tagger-infra
      - put: ecs-ami-id
        params:
          file: tested_ami/id

  - name: dw-al2-ecs-ami
    plan:
      - get: source_ami
        resource: ecs-ami-id
        trigger: true
        passed:
          - validate-ecs-ami
      - .: (( inject meta.plan.promote-ami ))
        config:
          params:
            AMI_NAME_PREFIX: "dw-al2-ecs-ami-"

  - name: dw-al2-ecs-ami-pr
    max_in_flight: 1
    plan:
      - get: dw-al2-ecs-ami-pr
        trigger: true
        version: every
      - get: dw-al2-base-ami-template
        trigger: false
      - put: dw-al2-ecs-ami-pr
        params:
          path: dw-al2-ecs-ami-pr
          status: pending
      - .: (( inject meta.plan.get-al2-hardened-ami ))
        trigger: false
      - .: (( inject meta.plan.generate-manifest ))
        input_mapping:
          source_ami: dw-al2-hardened-ami
        config:
          params:
            AMI_NAME: pr-dw-al2-ecs-ami
            SOURCE_AMI_NAME: dw-al2-hardened-ami-*
            SOURCE_AMI_OWNER: ((aws_account.management))
            AMI_USERS: ((aws_account.development))
            PROVISION_SCRIPT_KEYS: '["dw-al2-ecs-ami-pr/dw-al2-ecs-ami/dw-ecs-ami-install.sh"]'
            PROVISIONER_TYPE_FILE_SOURCE: "dw-al2-ecs-ami-pr/dw-al2-ecs-ami/"
      - .: (( inject meta.plan.packer-bootstrap ))
        input_mapping:
          source_config: dw-al2-ecs-ami-pr
          source_template: dw-al2-base-ami-template
      - .: (( inject meta.plan.build-ami ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
          inputs:
            - name: dw-al2-ecs-ami-pr
        on_failure:
          put: dw-al2-ecs-ami-pr
          params:
            path: dw-al2-ecs-ami-pr
            status: failure
        on_success:
          put: dw-al2-ecs-ami-pr
          params:
            path: dw-al2-ecs-ami-pr
            status: success
