resources:
  - name: dw-al2-hardened-ami-arm-config
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - dw-al2-hardened-ami-arm/*
        - ci/infra/jobs/build_amis_arm/dw-al2-hardened-ami-arm.yml

  - name: dw-al2-hardened-ami-arm-pr
    .: (( inject meta.resources.ami-builder-configs-pr ))
    source:
      paths:
        - dw-al2-hardened-ami-arm/*
        - ci/infra/jobs/build_amis_arm/dw-al2-hardened-ami-arm.yml

jobs:
  - name: dw-al2-untested-hardened-ami
    plan:
      - get: dw-al2-hardened-ami-arm-config
        trigger: true
      - get: dw-al2-base-ami-arm-template
        trigger: false
      - get: dw-al2-base-ami-arm
        trigger: true
      - .: (( inject meta.plan.generate-manifest ))
        input_mapping:
          source_ami: dw-al2-base-ami-arm
        config:
          params:
            AMI_NAME: dw-al2-untested-hardened-ami
            SOURCE_AMI_NAME: dw-al2-base-ami-arm-*
            SOURCE_AMI_OWNER: ((aws_account.management))
            PROVISION_SCRIPT_KEYS: '["dw-al2-hardened-ami-arm-config/dw-al2-hardened-ami-arm/hardening.sh","dw-al2-hardened-ami-arm-config/dw-al2-hardened-ami-arm/dw-hardened-ami-install.sh"]'
            PROVISIONER_TYPE_FILE_SOURCE: "dw-al2-hardened-ami-arm-config/dw-al2-hardened-ami-arm/"
      - .: (( inject meta.plan.packer-bootstrap ))
        input_mapping:
          source_config: dw-al2-hardened-ami-arm-config
          source_template: dw-al2-base-ami-arm-template
      - .: (( inject meta.plan.build-ami ))
        config:
          inputs:
            - name: dw-al2-hardened-ami-arm-config

  - name: dw-al2-hardened-ami-arm-pr
    max_in_flight: 1
    plan:
      - get: dw-al2-hardened-ami-arm-pr
        trigger: true
        version: every
      - get: dw-al2-base-ami-arm-template
        trigger: false
      - get: dw-al2-base-ami-arm
      - put: dw-al2-hardened-ami-arm-pr
        params:
          path: dw-al2-hardened-ami-arm-pr
          status: pending
      - .: (( inject meta.plan.generate-manifest ))
        input_mapping:
          source_ami: dw-al2-base-ami-arm
        config:
          params:
            AMI_NAME: pr-dw-al2-hardened-ami-arm
            SOURCE_AMI_NAME: dw-al2-base-ami-arm-*
            SOURCE_AMI_OWNER: ((aws_account.management))
            AMI_USERS: ((aws_account.development))
            PROVISION_SCRIPT_KEYS: '["dw-al2-hardened-ami-arm-pr/dw-al2-hardened-ami-arm/hardening.sh","dw-al2-hardened-ami-arm-pr/dw-al2-hardened-ami-arm/dw-hardened-ami-install.sh"]'
            PROVISIONER_TYPE_FILE_SOURCE: "dw-al2-hardened-ami-arm-pr/dw-al2-hardened-ami-arm/"
      - .: (( inject meta.plan.packer-bootstrap ))
        input_mapping:
          source_config: dw-al2-hardened-ami-arm-pr
          source_template: dw-al2-base-ami-arm-template
      - .: (( inject meta.plan.build-ami ))
        config:
          params:
            AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
          inputs:
            - name: dw-al2-hardened-ami-arm-pr
        on_failure:
          put: dw-al2-hardened-ami-arm-pr
          params:
            path: dw-al2-hardened-ami-arm-pr
            status: failure
        on_success:
          put: dw-al2-hardened-ami-arm-pr
          params:
            path: dw-al2-hardened-ami-arm-pr
            status: success

  - name: dw-al2-test-and-promote-hardened-ami
    max_in_flight: 1
    plan:
      - get: dw-al2-untested-hardened-ami
        trigger: true
      - get: aws-management-infrastructure
        trigger: false
      - get: aws-security-tools
        trigger: false
      - .: (( inject meta.plan.terraform-output-management ))
        config:
          params:
            TF_WORKSPACE: management
      - .: (( inject meta.plan.start-instance ))
        input_mapping:
          source_ami: dw-al2-untested-hardened-ami
        config:
          params:
            LAUNCH_TEMPLATE_OUTPUT_NAME: "hardened_test_launch_template"
      - .: (( inject meta.plan.run-inspector ))
      - .: (( inject meta.plan.evaluate-assessment-run))
        config:
          params:
            WHITELIST_NAME: whitelist_al2_hardened_ami
      - .: (( inject meta.plan.promote-ami ))
        input_mapping:
          source_ami: dw-al2-untested-hardened-ami
        config:
          params:
            AMI_NAME_PREFIX: "dw-al2-hardened-ami-arm-"
    ensure:
      do:
        - .: (( inject meta.plan.inspector-cleanup ))

  - name: dw-al2-weekly-test-hardened-ami
    max_in_flight: 1
    plan:
      - get: weekly-wednesday
        trigger: true
      - get: dw-al2-untested-hardened-ami
        trigger: true
      - get: aws-management-infrastructure
        trigger: false
      - get: aws-security-tools
        trigger: false
      - .: (( inject meta.plan.terraform-output-management ))
        config:
          params:
            TF_WORKSPACE: management
      - .: (( inject meta.plan.start-instance ))
        input_mapping:
          source_ami: dw-al2-untested-hardened-ami
        config:
          params:
            LAUNCH_TEMPLATE_OUTPUT_NAME: "hardened_test_launch_template"
      - .: (( inject meta.plan.run-inspector ))
      - .: (( inject meta.plan.evaluate-assessment-run))
        config:
          params:
            WHITELIST_NAME: whitelist_al2_hardened_ami
    ensure:
      do:
        - .: (( inject meta.plan.inspector-cleanup ))
    .: (( inject meta.plan.notify ))
    on_failure:
      params:
        attachments:
          - color: danger
            text: ":fire: Weekly AWS Inspector test of dw-al2-hardened-ami-arm has failed - non-whitelisted vulnerabilities found "
