groups:
  - name: al2-amis
    jobs:
      - dw-al2-base-ami
      - dw-al2-base-singlevol-ami
      - dw-al2-base-dualvol-ami
      - dw-al2-base-emr-ami
      - dw-al2-untested-hardened-ami
      - dw-al2-test-and-promote-hardened-ami
      - release-and-test-out-of-hours
      - untested-dw-al2-emr-ami
      - untested-dw-al2-hbase-ami
      - untested-dw-al2-ecs-ami
      - untested-dw-al2-concourse-ami
      - untested-dw-al2-analytical-env-emr-ami
      - untested-dw-al2-jvm-ami
      - validate-emr-ami
      - validate-hbase-ami
      - validate-ecs-ami
      - validate-concourse-ami
      - validate-analytical-env-emr-ami
      - validate-jvm-ami
      - dw-al2-emr-ami
      - dw-al2-hbase-ami
      - dw-al2-ecs-ami
      - dw-al2-concourse-ami
      - dw-al2-analytical-env-emr-ami
      - dw-al2-jvm-ami

  - name: pull-requests
    jobs:
      - dw-al2-base-ami-pr
      - dw-al2-base-emr-ami-pr
      - dw-al2-hardened-ami-pr
      - dw-al2-emr-ami-pr
      - dw-al2-hbase-ami-pr
      - dw-al2-ecs-ami-pr
      - dw-al2-concourse-ami-pr
      - dw-al2-analytical-env-emr-ami-pr
      - dw-al2-jvm-ami-pr

  - name: ami-weekly-test
    jobs:
      - dw-al2-weekly-test-hardened-ami

  - name: update-pipeline
    jobs:
      - update-pipeline
