resources:
  - name: aws-management-infrastructure
    type: git
    source:
      branch: master
      uri: https://((dataworks.enterprise_github_url))/dip/aws-management-infrastructure.git
      username: ((dataworks.enterprise_github_username))
      password: ((dataworks-secrets.enterprise_github_pat))
    check_every: 5m
    webhook_token: ((dataworks.concourse_github_webhook_token))

  - name: dw-al2-ami-template
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - generic_packer_template.json.j2

  - name: ami-builder-configs-update-pipeline
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - ci/*
        - aviator.yml

  - name: amzn2-ami-hvm
    type: ami
    check_every: 5m
    source:
      aws_role_arn: arn:aws:iam::((aws_account.management)):role/ci
      region: ((dataworks.aws_region))
      filters:
        is-public: true
        state: available
        name: amzn2-ami-hvm-*
        architecture: x86_64

  - name: hcs-amzn2-cis2-ami
    type: ami
    check_every: 5m
    source:
      aws_role_arn: arn:aws:iam::((aws_account.management)):role/ci
      region: ((dataworks.aws_region))
      filters:
        owner-id: ((dataworks.hcs_aws_account))
        is-public: false
        state: available
        name: AMZN2-AWS-CIS2-20*

  - name: hcs-amzn2-singlevol-cis2-ami
    type: ami
    check_every: 5m
    source:
      aws_role_arn: arn:aws:iam::((aws_account.management)):role/ci
      region: ((dataworks.aws_region))
      filters:
        owner-id: ((dataworks.hcs_aws_account))
        is-public: false
        state: available
        name: AMZN2-SINGLEVOL-AWS-CIS2-20*

  - name: hcs-amzn2emr-cis2-ami
    type: ami
    check_every: 5m
    source:
      aws_role_arn: arn:aws:iam::((aws_account.management)):role/ci
      region: ((dataworks.aws_region))
      filters:
        owner-id: ((dataworks.hcs_aws_account))
        is-public: false
        state: available
        name: AMZN2EMR-AWS-CIS2-20*

  - name: dw-al2-base-ami
    type: ami
    check_every: 5m
    source:
      aws_role_arn: arn:aws:iam::((aws_account.management)):role/ci
      region: ((dataworks.aws_region))
      filters:
        owner-id: ((aws_account.management))
        is-public: false
        state: available
        name: dw-al2-base-ami-*

  - name: dw-al2-hcs-backed-singlevol-ami
    type: ami
    check_every: 5m
    source:
      aws_role_arn: arn:aws:iam::((aws_account.management)):role/ci
      region: ((dataworks.aws_region))
      filters:
        owner-id: ((aws_account.management))
        is-public: false
        state: available
        name: dw-al2-hcs-backed-singlevol-ami-*

  # - name: dw-al2-hcs-backed-dualvol-ami
  #   type: ami
  #   check_every: 5m
  #   source:
  #     aws_role_arn: arn:aws:iam::((aws_account.management)):role/ci
  #     region: ((dataworks.aws_region))
  #     filters:
  #       owner-id: ((aws_account.management))
  #       is-public: false
  #       state: available
  #       name: dw-al2-hcs-backed-dualvol-ami-*

  - name: dw-al2-hcs-backed-emr-ami
    type: ami
    check_every: 5m
    source:
      aws_role_arn: arn:aws:iam::((aws_account.management)):role/ci
      region: ((dataworks.aws_region))
      filters:
        owner-id: ((aws_account.management))
        is-public: false
        state: available
        name: dw-al2-hcs-backed-emr-ami-*

  - name: dw-al2-emr-ami
    type: ami
    check_every: 5m
    source:
      aws_role_arn: arn:aws:iam::((aws_account.management)):role/ci
      region: ((dataworks.aws_region))
      filters:
        owner-id: ((aws_account.management))
        is-public: false
        state: available
        name: dw-al2-emr-ami-*

  - name: dw-al2-untested-hardened-ami
    type: ami
    check_every: 5m
    source:
      aws_role_arn: arn:aws:iam::((aws_account.management)):role/ci
      region: ((dataworks.aws_region))
      filters:
        owner-id: ((aws_account.management))
        is-public: false
        state: available
        name: dw-al2-untested-hardened-ami-*

  - name: dw-al2-hardened-ami
    type: ami
    check_every: 5m
    source:
      aws_role_arn: arn:aws:iam::((aws_account.management)):role/ci
      region: ((dataworks.aws_region))
      filters:
        owner-id: ((aws_account.management))
        is-public: false
        state: available
        name: dw-al2-hardened-ami-*

  - name: aws-security-tools
    type: git
    source:
      branch: master
      uri: https://((dataworks.enterprise_github_url))/dip/aws-security-tools.git
      username: ((dataworks.enterprise_github_username))
      password: ((dataworks-secrets.enterprise_github_pat))
    check_every: 5m
    webhook_token: ((dataworks.concourse_github_webhook_token))

  - name: dw-al2-emr-ami-config
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - dw-al2-emr-ami/*
        - ci/infra/jobs/build_amis/dw-al2-emr-ami.yml

  - name: dw-al2-emr-ami-pr
    .: (( inject meta.resources.ami-builder-configs-pr ))
    source:
      paths:
        - dw-al2-emr-ami/*
        - ci/infra/jobs/build_amis/dw-al2-emr-ami.yml

  - name: dw-al2-hbase-ami-config
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - dw-al2-hbase-ami/*
        - ci/infra/jobs/build_amis/dw-al2-hbase-ami.yml

  - name: dw-al2-hbase-ami-pr
    .: (( inject meta.resources.ami-builder-configs-pr ))
    source:
      paths:
        - dw-al2-hbase-ami/*
        - ci/infra/jobs/build_amis/dw-al2-hbase-ami.yml

  - name: dw-al2-jvm-ami-config
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - dw-al2-jvm-ami/*
        - ci/infra/jobs/build_amis/dw-al2-jvm-ami.yml

  - name: dw-al2-jvm-ami-pr
    .: (( inject meta.resources.ami-builder-configs-pr ))
    source:
      paths:
        - dw-al2-jvm-ami/*
        - ci/infra/jobs/build_amis/dw-al2-jvm-ami.yml

  - name: analytical-dataset-generation
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - results/analytical-dataset-generation.test

  - name: aws-mongo-latest
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - results/aws-mongo-latest.test

  - name: pdm-dataset-generation
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - results/pdm-dataset-generation.test

  - name: aws-clive
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - results/aws-clive.test

  - name: aws-cyi-infrastructure
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - results/aws-cyi-infrastructure.test

  - name: aws-uc-feature-infrastructure
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - results/aws-uc-feature-infrastructure.test

  - name: analytical-env
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - results/analytical-env.test

  - name: concourse
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - results/concourse.test

  - name: aws-internal-compute-hbase-ami-test
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - results/aws-internal-compute-hbase-ami-test.test
  
  - name: aws-internal-compute-jvm-ami-test
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - results/aws-internal-compute-jvm-ami-test.test

  - name: aws-crypto-dks
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - results/aws-crypto.test

  - name: dataworks-aws-ingest-consumers
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - results/dataworks-aws-ingest-consumers.test

  - name: aws-snapshot-sender
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - results/aws-snapshot-sender.test

  - name: metrics-infrastructure
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - results/metrics-infrastructure.test

  - name: ingestion-ecs-cluster
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - results/ingestion-ecs-cluster.test

  - name: data-egress
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - results/data-egress.test

  - name: orchestration-service
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - results/orchestration-service.test

  - name: s3-object-tagger-infra
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - results/s3-object-tagger-infra.test

  - name: dw-al2-hardened-ami-config
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - dw-al2-hardened-ami/*
        - ci/infra/jobs/build_amis/dw-al2-hardened-ami.yml

  - name: dw-al2-hardened-ami-pr
    .: (( inject meta.resources.ami-builder-configs-pr ))
    source:
      paths:
        - dw-al2-hardened-ami/*
        - ci/infra/jobs/build_amis/dw-al2-hardened-ami.yml

  - name: dw-al2-base-ami-config
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - dw-al2-base-ami/*
        - ci/infra/jobs/build_amis/dw-al2-base-ami.yml

  - name: dw-al2-base-ami-pr
    .: (( inject meta.resources.ami-builder-configs-pr ))
    source:
      paths:
        - dw-al2-base-ami/*
        - generic_packer_template.json.j2
        - ci/infra/jobs/build_amis/dw-al2-base-ami.yml

  # - name: dw-al2-hcs-backed-ami-config
  #   .: (( inject meta.resources.ami-builder-configs ))
  #   source:
  #     paths:
  #       - dw-al2-hcs-backed-ami/*
  #       - ci/infra/jobs/build_amis/dw-al2-base-ami.yml
  
  - name: dw-al2-hcs-singlevol-backed-ami-config
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - dw-al2-hcs-backed-ami/*
        - ci/infra/jobs/build_amis/dw-al2-hcs-backed-singlevol-ami.yml
  
  - name: dw-al2-hcs-dualvol-backed-ami-config
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - dw-al2-hcs-backed-ami/*
        - ci/infra/jobs/build_amis/dw-al2-hcs-backed-ami.yml

  - name: dw-al2-hcs-backed-emr-ami-config
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - dw-al2-hcs-backed-ami/*
        - ci/infra/jobs/build_amis/dw-al2-hcs-backed-emr-ami.yml

  # - name: dw-al2-hcs-backed-ami-pr
  #   .: (( inject meta.resources.ami-builder-configs-pr ))
  #   source:
  #     paths:
  #       - dw-al2-hcs-backed-ami/*
  #       - generic_packer_template.json.j2
  #       - ci/infra/jobs/build_amis/dw-al2-base-ami.yml
  #       - ci/infra/jobs/build_amis/dw-al2-hcs-backed-ami.yml
  #       - ci/infra/jobs/build_amis/dw-al2-hcs-backed-emr-ami.yml
  #       - ci/infra/jobs/build_amis/dw-al2-hcs-backed-singlevol-ami.yml
  
  - name: dw-al2-hcs-backed-dualvol-ami-pr
    .: (( inject meta.resources.ami-builder-configs-pr ))
    source:
      paths:
      - dw-al2-hcs-backed-ami/*
      - generic_packer_template.json.j2  
      - ci/infra/jobs/build_amis/dw-al2-hcs-backed-ami.yml

  - name: dw-al2-hcs-backed-singlevol-ami-pr
    .: (( inject meta.resources.ami-builder-configs-pr ))
    source:
      paths:
      - dw-al2-hcs-backed-ami/*
      - generic_packer_template.json.j2  
      - ci/infra/jobs/build_amis/dw-al2-hcs-backed-singlevol-ami.yml
 
  - name: dw-al2-hcs-backed-emr-ami-pr
    .: (( inject meta.resources.ami-builder-configs-pr ))
    source:
      paths:
        - dw-al2-hcs-backed-ami/*
        - generic_packer_template.json.j2
        - ci/infra/jobs/build_amis/dw-al2-hcs-backed-emr-ami.yml

  - name: dw-al2-concourse-ami-config
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - dw-al2-concourse-ami/*
        - ci/infra/jobs/build_amis/dw-al2-concourse-ami.yml

  - name: dw-al2-concourse-ami-pr
    .: (( inject meta.resources.ami-builder-configs-pr ))
    source:
      paths:
        - dw-al2-concourse-ami/*
        - ci/infra/jobs/build_amis/dw-al2-concourse-ami.yml

  - name: dw-al2-ecs-ami-config
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - dw-al2-ecs-ami/*
        - ci/infra/jobs/build_amis/dw-al2-ecs-ami.yml

  - name: dw-al2-ecs-ami-pr
    .: (( inject meta.resources.ami-builder-configs-pr ))
    source:
      paths:
        - dw-al2-ecs-ami/*
        - ci/infra/jobs/build_amis/dw-al2-ecs-ami.yml

  - name: dw-al2-analytical-env-emr-ami-config
    .: (( inject meta.resources.ami-builder-configs ))
    source:
      paths:
        - dw-al2-analytical-env-emr-ami/*
        - ci/infra/jobs/build_amis/dw-al2-analytical-env-emr-ami.yml

  - name: dw-al2-analytical-env-emr-ami-pr
    .: (( inject meta.resources.ami-builder-configs-pr ))
    source:
      paths:
        - dw-al2-analytical-env-emr-ami/*
        - ci/infra/jobs/build_amis/dw-al2-analytical-env-emr-ami.yml

  - name: concourse-release
    type: github-release
    source:
      owner: concourse
      repository: concourse
      access_token: ((dataworks-secrets.concourse_github_pat))
    check_every: 1h

  - name: weekly-wednesday
    source:
      start: 3:00 AM
      stop: 4:00 AM
      days: [Wednesday]
    type: time

  - name: slack
    type: slack-notification
    source:
      url: ((dataworks.slack_webhook_url))

  - name: base-ami-id
    type: file

  - name: hcs-backed-singlevol-ami-id
    type: file

  - name: hcs-backed-dualvol-ami-id
    type: file

  - name: hcs-backed-emr-ami-id
    type: file

  - name: hardened-ami-id
    type: file

  - name: emr-ami-id
    type: file

  - name: hbase-ami-id
    type: file

  - name: jvm-ami-id
    type: file

  - name: untested-dw-al2-emr-ami
    type: file

  - name: untested-dw-al2-hbase-ami
    type: file

  - name: untested-dw-al2-jvm-ami
    type: file

  - name: ecs-ami-id
    type: file

  - name: untested-dw-al2-ecs-ami
    type: file

  - name: concourse-ami-id
    type: file

  - name: untested-dw-al2-concourse-ami
    type: file

  - name: untested-dw-al2-analytical-env-emr-ami
    type: file

  - name: analytical-env-emr-ami-id
    type: file

  - name: utc-7pm-trigger
    type: time
    source:
      location: UTC
      start: 19:00
      stop: 20:00
