resources:
  - name: aws-management-infrastructure
    type: git
    source:
      branch: master
      uri: https://((dataworks.enterprise_github_url))/dip/aws-management-infrastructure.git
      username: ((dataworks.enterprise_github_username))
      password: ((dataworks-secrets.enterprise_github_pat))
    check_every: 720h
    webhook_token: ((dataworks.concourse_github_webhook_token))

  - name: dw-al2-base-ami
    type: ami
    check_every: 5m
    source:
      aws_role_arn: arn:aws:iam::((dataworks.aws_management_acc)):role/ci
      region: ((dataworks.aws_region))
      filters:
        owner-id: ((dataworks.aws_management_acc))
        is-public: false
        state: available
        name: dw-al2-base-ami-*

  - name: dw-al2-untested-hardened-ami
    type: ami
    check_every: 5m
    source:
      aws_role_arn: arn:aws:iam::((dataworks.aws_management_acc)):role/ci
      region: ((dataworks.aws_region))
      filters:
        owner-id: ((dataworks.aws_management_acc))
        is-public: false
        state: available
        name: dw-al2-untested-hardened-ami-*

  - name: dw-al2-hardened-ami
    type: ami
    check_every: 5m
    source:
      aws_role_arn: arn:aws:iam::((dataworks.aws_management_acc)):role/ci
      region: ((dataworks.aws_region))
      filters:
        owner-id: ((dataworks.aws_management_acc))
        is-public: false
        state: available
        name: dw-al2-hardened-ami-*

  - name: aws-security-tools
    type: git
    source:
      branch: master
      uri: https://((dataworks.enterprise_github_url))/dip/aws-security-tools.git
      username: ((dataworks.enterprise_github_username))
      password: ((dataworks-secrets.enterprise_github_pat))
    check_every: 720h
    webhook_token: ((dataworks.concourse_github_webhook_token))

  - name: weekly-wednesday
    source:
      start: 3:00 AM
      stop: 4:00 AM
      days: [Wednesday]
    type: time

  - name: slack
    type: slack-notification
    source:
      url: ((dataworks.slack_webhook_url))
